"""add device family

Revision ID: 2bcde9e3a869
Revises: 785f72949598
Create Date: 2026-09-23 13:11:05.703107

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '2bcde9e3a869'
down_revision: Union[str, Sequence[str], None] = '785f72949598'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('device_family', sa.String(length=32), server_default='simulation', nullable=False))
    op.create_index('ix_devices_family', 'devices', ['device_family'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_devices_family', table_name='devices')
    op.drop_column('devices', 'device_family')
    # ### end Alembic commands ###